title: OpenSourcing.me
author: Marco Zink
url: https://opensourcing.me
remote_theme: "jeffreytse/jekyll-theme-yat"
repository: "opensourcingme/opensourcingme.github.io"
home:
  heading: "OpenSourcing.me"
  subheading: "Taking OpenSource to you"
